---
version: "3"
services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 13448:443
      - 10808:80
    environment:
      - "NGINX_SSL_CERTIFICATE=/etc/letsencrypt/live/home.lymer.ca/fullchain.pem"
      - "NGINX_SSL_CERTIFICATE_KEY=/etc/letsencrypt/live/home.lymer.ca/privkey.pem"
    volumes:
      - ./workloads/nginx/docker-entrypoint.d/50-hot-reload.sh:/docker-entrypoint.d/50-hot-reload.sh:ro
      - ./workloads/nginx/conf.d/custom:/etc/nginx/conf.d/custom:ro
      - ./workloads/nginx/templates:/etc/nginx/templates:ro
      - ./docker/data/etc/letsencrypt:/etc/letsencrypt:ro

  certbot:
    image: certbot/dns-google
    volumes:
      - ./docker/data/etc/letsencrypt/:/etc/letsencrypt
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    entrypoint:
      - sh
      - -c
      - |
        trap exit INT TERM
        while true; do
          certbot certonly \
            --agree-tos \
            --noninteractive \
            --preferred-challenges dns \
            --domain "home.lymer.ca" \
            --domain "*.home.lymer.ca" \
            --dns-google \
            --dns-google-project matthewlymer-production
          sleep 12h
        done &
        wait

  homelink:
    build:
      context: workloads/homelink
      dockerfile: ./Dockerfile
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    environment:
      - "CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=/root/.config/gcloud/application_default_credentials.json"
    entrypoint:
      - sh
      - -c
      - |
        trap exit INT TERM
        while true; do
          ./update-dns-records.sh
          sleep 15m
        done &
        wait

  actual:
    image: actualbudget/actual-server:sha-3cab9a3-alpine # May 11, 2025 at 8:57 pm
    volumes:
      - ./workloads/actual/data:/data

  jellyfin:
    image: jellyfin/jellyfin
    volumes:
      - ./workloads/jellyfin/data/config:/config
      - ./workloads/jellyfin/data/cache:/cache
      - ./workloads/jellyfin/data/media/music:/media/music:ro
      - ./workloads/jellyfin/data/media/torrents:/media/torrents:ro
