# Note about DNS:
#   using DOCKER_HOST results in the host getting the wrong DNS
#   configuration, so we use known good public nameservers
#   instead of the misconfigured ones

services:
  nginx:
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /share/homes/qnappy/home-automation/nginx/docker-entrypoint.d/50-hot-reload.sh:/docker-entrypoint.d/50-hot-reload.sh:ro
      - /share/homes/qnappy/home-automation/nginx/conf.d/custom:/etc/nginx/conf.d/custom:ro
      - /share/homes/qnappy/home-automation/nginx/templates:/etc/nginx/templates:ro
      - /share/homes/qnappy/home-automation/letsencrypt:/etc/letsencrypt:ro

  certbot:
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /share/homes/qnappy/home-automation/letsencrypt:/etc/letsencrypt
      - /share/homes/qnappy/home-automation/certbot_sa_key.json:/root/.config/gcloud/application_default_credentials.json:ro
      
  homelink:
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /share/homes/qnappy/home-automation/homelink_sa_key.json:/root/.config/gcloud/application_default_credentials.json:ro
