---
version: "3"
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 8443:443
    volumes:
      - ./resources/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/etc_letsencrypt:/etc/letsencrypt
